#ifndef ENUM_H
#define ENUM_H
typedef enum {
    ADD_BOOK = 1,
    REMOVE_BOOK,
    UPDATE_BOOK,
    VIEW_BOOKS,
    ADD_STUDENT,
    VIEW_STUDENTS,
    ADD_DEPARTMENT,
    VIEW_DEPARTMENTS,
    ADD_STAFF,
    VIEW_STAFF,
    RECORD_BORROWED_BOOK,
    VIEW_BORROWED_BOOKS,
    RECORD_RETURNED_BOOK,
    VIEW_RETURNED_BOOKS,
    SORT_BOOKS_BY_NAME,
    SORT_AUTHORS,
    EXIT
} MenuOption;

#endif // ENUM_H
